name: BUILD_TOOLS_IVERILOG

on:
  workflow_dispatch:

jobs:

  build4windows:
    runs-on: windows-latest
    env:
      BUILD_TOOLS: iverilog
      MSYS2_PATH_TYPE: inherit
      CHERE_INVOKING: yes
    defaults:
      run:
        shell: cmd
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Run the build script
        run: |
          set MSYSTEM=MINGW64
          C:\msys64\usr\bin\bash.exe -lc "cd $GITHUB_WORKSPACE && export BUILD_ARCHS='mingw32-w64-x86_64' && bash main_flow.sh"
          set MSYSTEM=MINGW32
          C:\msys64\usr\bin\bash.exe -lc "cd $GITHUB_WORKSPACE && export BUILD_ARCHS='mingw32-w64-i686' && bash main_flow.sh"
      - name: Bundle the chocolatey package
        run: C:\msys64\usr\bin\bash.exe -lc "cd $GITHUB_WORKSPACE && bash create_chocolatey_packages.sh"
      - name: Publish packages
        run: C:\msys64\usr\bin\bash.exe -lc "cd $GITHUB_WORKSPACE && bash publish_github_release.sh"
  
  build4linux:
    runs-on: ubuntu-latest
    env: 
      BUILD_TOOLS: iverilog
      BUILD_ARCHS: linux-i686 linux-x86_64
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Run the build script
        run: cd $GITHUB_WORKSPACE && bash main_flow.sh
      - name: Publish packages
        run: cd $GITHUB_WORKSPACE && bash publish_github_release.sh
